### ISSUE TITLE
Error at advform-plugin.php in advform 0.9.1.3 production

### ISSUE THREAD

**Issue by mondarse** [bitcero/advform#1]
Have found this php error shown in rmcommon plugings manager (/modules/rmcommon/plugins.php):

Warning: Undefined variable: options in archive /modules/rmcommon/plugins/advform/advform-plugin.php amd line 50
´´´
    public function options(){

```
    //require 'include/options.php';
    return $options;

}
```

´´´

I looks like there is no $options variable defined in class "class AdvformCUPlugin"

**Comment by bitcero** [comment]
Fixed. Ready for next update. Thanks!
